[tool.poetry]
name = "scrapegraphaisub"
version = "0.0.12b3"
description = "A first semantic versioned Scrapegraph fork by subzero team"
authors = [
    "simone pulcini <pulcini@prova.prova>",
    "luigi corollo <corollo@prova.prova>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/subzero-team/Scrapegraph-ai"
repository = "https://github.com/subzero-team/Scrapegraph-ai"
documentation = "https://github.com/subzero-team/Scrapegraph-ai"
keywords = ["scrapegraph", "scrapegraphai", "langchain", "ai", "artificial intelligence", "gpt", "machine learning", "rag", "nlp", "natural language processing", "openai", "scraping", "web scraping", "web scraping library", "web scraping tool", "webscraping", "graph"]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
[tool.poetry.dependencies]
python = ">3.9,<3.9.7 || >3.9.7,<3.12"
langchain = "0.1.6"
langchain_community = "0.0.19"
langchain_core = "0.1.22"
langchain_openai = "0.0.5"
langchain_google_genai = "0.0.11"
html2text = "2020.1.16"
faiss-cpu = "1.7.4"
beautifulsoup4 = "4.12.3"
trulens_eval = "0.23.0"
pandas = "2.0.3"
python-dotenv = "1.0.1"
tiktoken = {version = ">=0.5.2,<0.6.0"}
tqdm = "4.66.1"
graphviz = "0.20.1"

[tool.poetry.dev-dependencies]
pytest = "8.0.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "7.1.2"
sphinx-rtd-theme = "2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

